# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 872bce3388bf3359d83a08023d58ef3710ae9eb4b1fda83923db48afac559c9b86b8753f925278f0e4a8f9640f0a9ebefa61abd86a182fa2300d5c7d1ed2e7c1

test:
  secret_key_base: d29f311151217f188dfcf9c4a639a1cd9cc5d3980991b490e98dba44f36728791d7ebcd29a82d877c6304c84a3d6a6623b6346dfc4be316b99d8c2ce79b5e41d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
